/**
 * Union type containing all standard keyboard key values.
 * Based on the W3C UI Events KeyboardEvent key Values specification.
 */
export type KeyboardKey =
    // Modifier Keys
    | "Alt"
    | "AltGraph"
    | "CapsLock"
    | "Control"
    | "Fn"
    | "FnLock"
    | "Meta"
    | "NumLock"
    | "ScrollLock"
    | "Shift"
    | "Symbol"
    | "SymbolLock"
    | "Hyper"
    | "Super"

    // Whitespace Keys
    | "Enter"
    | "Tab"
    | " "

    // Navigation Keys
    | "ArrowDown"
    | "ArrowLeft"
    | "ArrowRight"
    | "ArrowUp"
    | "End"
    | "Home"
    | "PageDown"
    | "PageUp"

    // Editing Keys
    | "Backspace"
    | "Clear"
    | "Copy"
    | "CrSel"
    | "Cut"
    | "Delete"
    | "EraseEof"
    | "ExSel"
    | "Insert"
    | "Paste"
    | "Redo"
    | "Undo"

    // UI Keys
    | "Accept"
    | "Again"
    | "Attn"
    | "Cancel"
    | "ContextMenu"
    | "Escape"
    | "Execute"
    | "Find"
    | "Help"
    | "Pause"
    | "Play"
    | "Props"
    | "Select"
    | "ZoomIn"
    | "ZoomOut"

    // Device Keys
    | "BrightnessDown"
    | "BrightnessUp"
    | "Eject"
    | "LogOff"
    | "Power"
    | "PowerOff"
    | "PrintScreen"
    | "Hibernate"
    | "Standby"
    | "WakeUp"

    // IME and Composition Keys
    | "AllCandidates"
    | "Alphanumeric"
    | "CodeInput"
    | "Compose"
    | "Convert"
    | "Dead"
    | "FinalMode"
    | "GroupFirst"
    | "GroupLast"
    | "GroupNext"
    | "GroupPrevious"
    | "ModeChange"
    | "NextCandidate"
    | "NonConvert"
    | "PreviousCandidate"
    | "Process"
    | "SingleCandidate"

    // Korean Keyboard Keys
    | "HangulMode"
    | "HanjaMode"
    | "JunjaMode"

    // Japanese Keyboard Keys
    | "Eisu"
    | "Hankaku"
    | "Hiragana"
    | "HiraganaKatakana"
    | "KanaMode"
    | "KanjiMode"
    | "Katakana"
    | "Romaji"
    | "Zenkaku"
    | "ZenkakuHankaku"

    // Function Keys
    | "F1" | "F2" | "F3" | "F4" | "F5" | "F6"
    | "F7" | "F8" | "F9" | "F10" | "F11" | "F12"
    | "F13" | "F14" | "F15" | "F16" | "F17" | "F18"
    | "F19" | "F20" | "F21" | "F22" | "F23" | "F24"
    | "Soft1" | "Soft2" | "Soft3" | "Soft4"

    // Phone Keys
    | "AppSwitch"
    | "Call"
    | "Camera"
    | "CameraFocus"
    | "EndCall"
    | "GoBack"
    | "GoHome"
    | "HeadsetHook"
    | "LastNumberRedial"
    | "Notification"
    | "MannerMode"
    | "VoiceDial"

    // Multimedia Keys
    | "ChannelDown"
    | "ChannelUp"
    | "MediaFastForward"
    | "MediaPause"
    | "MediaPlay"
    | "MediaPlayPause"
    | "MediaRecord"
    | "MediaRewind"
    | "MediaStop"
    | "MediaTrackNext"
    | "MediaTrackPrevious"

    // Audio Control Keys
    | "AudioBalanceLeft"
    | "AudioBalanceRight"
    | "AudioBassDown"
    | "AudioBassBoostDown"
    | "AudioBassBoostToggle"
    | "AudioBassBoostUp"
    | "AudioBassUp"
    | "AudioFaderFront"
    | "AudioFaderRear"
    | "AudioSurroundModeNext"
    | "AudioTrebleDown"
    | "AudioTrebleUp"
    | "AudioVolumeDown"
    | "AudioVolumeUp"
    | "AudioVolumeMute"
    | "MicrophoneToggle"
    | "MicrophoneVolumeDown"
    | "MicrophoneVolumeUp"
    | "MicrophoneVolumeMute"

    // TV Control Keys
    | "TV"
    | "TV3DMode"
    | "TVAntennaCable"
    | "TVAudioDescription"
    | "TVAudioDescriptionMixDown"
    | "TVAudioDescriptionMixUp"
    | "TVContentsMenu"
    | "TVDataService"
    | "TVInput"
    | "TVInputComponent1"
    | "TVInputComponent2"
    | "TVInputComposite1"
    | "TVInputComposite2"
    | "TVInputHDMI1"
    | "TVInputHDMI2"
    | "TVInputHDMI3"
    | "TVInputHDMI4"
    | "TVInputVGA1"
    | "TVMediaContext"
    | "TVNetwork"
    | "TVNumberEntry"
    | "TVPower"
    | "TVRadioService"
    | "TVSatellite"
    | "TVSatelliteBS"
    | "TVSatelliteCS"
    | "TVSatelliteToggle"
    | "TVTerrestrialAnalog"
    | "TVTerrestrialDigital"
    | "TVTimer"

    // Media Controller Keys
    | "AVRInput"
    | "AVRPower"
    | "ColorF0Red"
    | "ColorF1Green"
    | "ColorF2Yellow"
    | "ColorF3Blue"
    | "ColorF4Grey"
    | "ColorF5Brown"
    | "ClosedCaptionToggle"
    | "Dimmer"
    | "DisplaySwap"
    | "DVR"
    | "Exit"
    | "FavoriteClear0"
    | "FavoriteClear1"
    | "FavoriteClear2"
    | "FavoriteClear3"
    | "FavoriteRecall0"
    | "FavoriteRecall1"
    | "FavoriteRecall2"
    | "FavoriteRecall3"
    | "FavoriteStore0"
    | "FavoriteStore1"
    | "FavoriteStore2"
    | "FavoriteStore3"
    | "Guide"
    | "GuideNextDay"
    | "GuidePreviousDay"
    | "Info"
    | "InstantReplay"
    | "Link"
    | "ListProgram"
    | "LiveContent"
    | "Lock"
    | "MediaApps"
    | "MediaAudioTrack"
    | "MediaLast"
    | "MediaSkipBackward"
    | "MediaSkipForward"
    | "MediaStepBackward"
    | "MediaStepForward"
    | "MediaTopMenu"
    | "NavigateIn"
    | "NavigateNext"
    | "NavigateOut"
    | "NavigatePrevious"
    | "NextFavoriteChannel"
    | "NextUserProfile"
    | "OnDemand"
    | "Pairing"
    | "PinPDown"
    | "PinPMove"
    | "PinPToggle"
    | "PinPUp"
    | "PlaySpeedDown"
    | "PlaySpeedReset"
    | "PlaySpeedUp"
    | "RandomToggle"
    | "RcLowBattery"
    | "RecordSpeedNext"
    | "RfBypass"
    | "ScanChannelsToggle"
    | "ScreenModeNext"
    | "Settings"
    | "SplitScreenToggle"
    | "STBInput"
    | "STBPower"
    | "Subtitle"
    | "Teletext"
    | "VideoModeNext"
    | "Wink"
    | "ZoomToggle"

    // Application Keys
    | "LaunchApplication1"
    | "LaunchApplication2"
    | "LaunchCalendar"
    | "LaunchContacts"
    | "LaunchMail"
    | "LaunchMediaPlayer"
    | "LaunchMusicPlayer"
    | "LaunchPhone"
    | "LaunchScreenSaver"
    | "LaunchSpreadsheet"
    | "LaunchWebBrowser"
    | "LaunchWebCam"
    | "LaunchWordProcessor"

    // Browser Keys
    | "BrowserBack"
    | "BrowserFavorites"
    | "BrowserForward"
    | "BrowserHome"
    | "BrowserRefresh"
    | "BrowserSearch"
    | "BrowserStop"

    // Numeric Keys (0-9)
    | "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"

    // Letter Keys (a-z, A-Z)
    | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m"
    | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
    | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M"
    | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"

    // Special Characters
    | "!" | "@" | "#" | "$" | "%" | "^" | "&" | "*" | "(" | ")"
    | "-" | "_" | "=" | "+" | "[" | "]" | "{" | "}"
    | "\\" | "|" | ";" | ":" | "'" | "\"" | "," | "." | "/" | "?"
    | "<" | ">" | "`" | "~"

    // Multimedia Numpad Keys
    | "Key11"
    | "Key12"

    // Special Value
    | "Unidentified";